plugins {
    id "com.android.application"
}

android {
    namespace "com.jon.facebatch"
    compileSdk 35

    defaultConfig {
        applicationId "com.jon.facebatch"
        minSdk 29
        targetSdk 34
        versionCode 10
        versionName "0.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
